version: '3.7'
services:
  app:
#    platform: linux/x86_64
    platform: linux/arm64
    build: "./"
    command: jekyll serve --force_polling
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
    environment:
      JEKYLL_ENV: docker
